### ISSUE TITLE
Change episode number

### ISSUE THREAD

**Issue by bornout** [Atelier-Shiori/Shukofukurou-iOS#14]
**Informations:**
IPhone iOS 13.3.1
Shukofukurou Testflight 2.0.5

**Problem:**
When i try to change the episode number with the + button it jumps direct to 101. Here for example one piece.

**Screenshots:**
![D6AD3C01-C6A3-454E-8A04-49825D09B2CB](https://user-images.githubusercontent.com/1838271/76563105-08e89e00-64a7-11ea-8b6d-2592c194334f.png)
![88BECF2E-D5CB-44D8-A65F-AFC266E206F3](https://user-images.githubusercontent.com/1838271/76563122-130a9c80-64a7-11ea-876d-c88318792d6d.png)

**Comment by bornout** [comment]
I try it already with some other series. Same result when the number is over 101.

**Comment by moyitpro** [comment]
I wasn't able to reproduce this issue. With MyAnimeList, I searched for One Piece, entered 398. After dismissing the keyboard, I pressed the stepper button and it went to 399. I have modified the behavior that when the stepper is pressed, the keyboard is dismissed, but the value does not change. Incrementing the second time will increment 398 for instance to 399. This should update the stepper with the updated value in the text field before incrementing.

Series with a total episode number of 0 will always set the stepper max value of 999999999. Otherwise, it's the episode total of the title if the total episodes are greater than 0. So the max value issue with the stepper shouldn't be an issue.

I will be uploading a test build, 2.0.6 (yes, I accidentally incremented the version number too much for the last release, which should be 2.0.4) to TestFlight. If you will have issues, record a video screen capture on your iPhone showing the stepper behavior and I will look into it more.

**Comment by bornout** [comment]
Version 2.0.6
![62FD8316-BF48-431E-8FAB-D054C5180E09](https://user-images.githubusercontent.com/1838271/77000448-b6046000-6958-11ea-8e3e-268f537acc5a.gif)

**Comment by moyitpro** [comment]
Figured out the error. The maximum stepper value was being set after the value of the stepper is set. If the progress is higher than 100, it would reset to 100 when you increase or decrease the stepper. If you change the value after the title information is loaded, that behavior doesn't happen. The behavior is now fixed as seen below.

![XGWI4356 2020-03-18 18_14_39](https://user-images.githubusercontent.com/161183/77012566-906d5b80-6944-11ea-91ee-dfd46090addf.gif)

Fixed with https://github.com/Atelier-Shiori/Shukofukurou-iOS/commit/40dae849c78e40b4a1bbd6bf1591e077b4ea8935
