### ISSUE TITLE
No Mangas when I use Myanimelist

### ISSUE THREAD

**Issue by bornout** [Atelier-Shiori/Shukofukurou-iOS#15]
**Describe the bug**
When i use myanimelist as service and i search for a manga it don’t show anything. Anilist and Kitsu are working.

**To Reproduce**
Service to Myanimelist > Search > Manga > 
Type for example One Piece > Enter

**Expected behavior**
To see all Mangas with the words „one piece“ in the name.

**Screenshots**
![BA7887ED-A770-426F-8FA7-09A984FBCF36](https://user-images.githubusercontent.com/1838271/76680101-3ab44e80-65e6-11ea-8228-791b0d823aea.png)

**Smartphone (please complete the following information):**
 - Device: iPhone Xs Max
 - OS: iOS 13.3.1
 - Shukofukurou Testflight 2.0.5

**Comment by moyitpro** [comment]
fixed with https://github.com/Atelier-Shiori/Hakuchou/commit/7510f7d6669aa7ae2c10d586947b64d1a81e8a0f

Apparently, the NSFW field for manga search wasn't included, which caused all the results to get filtered. 
![Screen-Shot-2020-03-15-at-12 24 43-PM](https://user-images.githubusercontent.com/161183/76705700-3ce6dd80-66b8-11ea-8f8c-45c609b97760.jpg)
